### ISSUE TITLE
Add running automation from local script/executable

### ISSUE THREAD

**Issue by ms2jpg** [SecurityBrewery/catalyst#430]
Hi, we are going to deploy Catalyst on Kubernetes, but our devops guy told us we can't mount docker socket to container in order to run automation script in containers. Is there any way to run local script in automation tasks?

Cheers

**Comment by cugu** [comment]
Hi, no currently that is not possible.

**Comment by ms2jpg** [comment]
Any plans on creating such mechanism? This would allow running Catalyst on k8s, openshift or any public cloud available and would be much appreciated.

**Comment by cugu** [comment]
I would stick with uniform docker containers instead of adding local script execution. Containers have a more isolated runtime and deployment mechanism compared to scripts.

So the way forward for k8s and alike platforms would be to create an integration that uses the API of those platforms to orchestrate containers.
